In [5]:
import pandas as pd
import requests
path = "https://api.airtable.com/v0/appu8ocaGPbj3Vt2k/indicators?view=indicatorSorting"
readOnlyKey = 'pattDYj5xTUxYtdsI.d8be15f625755afe3659c505731a777c3eebd5fc9f2ab822a567e24a47e824b7'

headers =  {
          'Content-Type': 'application/json',
          'Authorization': f'Bearer {readOnlyKey}'
          }

r = requests.get(path, headers=headers )
data = r.json()

data = data['records']
data

[{'id': 'recY1xFTlQIySFNXy',
  'createdTime': '2024-06-10T19:08:07.000Z',
  'fields': {'Callout_text_1': '### **Microplastics**\n\nWhile floatable debris in the Estuary seems to be decreasing, the same cannot be said for microplastics. Non-biodegradable single use plastics never disappear; exposed to the sun and other forces, they break up into smaller and smaller pieces. Other sources include particles from tires, paint, premanufacture pellets (called nurdles), and microfibers - shed from washing clothing made from synthetic fabrics. Regionally, the kind of plastic most prevalent and the primary source, amongst stormwater, wastewater, and combined sewage overflow, vary throughout the Estuary.  \nThere is no standardized monitoring protocol for collecting microplastics data, though more research is undertaken every year, adding to our collective understanding of the problem. In addition to characterizing the scope of microplastic pollution, scientists are also studying the effects these plastics are having on our ecosystem, particularly at vulnerable life stages for animals, and how these plastics absorb and transport contaminants.  \nMany recent local studies highlight the ubiquitousness of microplastics in the Hudson-Raritan Estuary waters`1,2,3` and biota`4`. For example, one recent study found microfibers in surface water samples along the entire length of the Hudson River and estimates that the Hudson’s contribution to the Atlantic Ocean may be more than 300 million microfibers per day`5`. This issue is not limited to our estuary, as microplastics are present throughout global oceans, seas, and coastal systems. A recent world-wide analysis found that microplastics in coastal systems are in an apparent steady state making it difficult to predict plastic sources`6`.  \nThough microplastics are clearly a complex and pervasive challenge, there is also recent research that provides hope and solutions. For example, some fish appear to be preferentially avoiding microplastics`7` and bioretention basins, vegetated depressions used to slow and treat on-site stormwater runoff, can effectively capture microplastics in stormwater`8`.\n\n',
   'Trend': 'trend_up_green',
   'Viz-1': [{'id': 'att9guhUfwBilljZB',
     'width': 3750,
     'height': 2430,
     'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/PWFBzZ98ql7FPApwo5GRkg/hB0ERGllJTGGtCeyhGB-NKNTjId8O-KKTZzdCj-J2g3FluGYOJkdOGkg35DlcC3at9Kr4sHfmZyfbCgjyQCFMfhWXZ4hFZuJE9lviEDz7Y4lOC9BSSyq8z5rOmN4myZwp5EYqqrcY0AH3l4PDrcK_SqBvVYtnJG9aHOzXUR-i6e7hKvN_KqRxNBlTdgxVUu7/Jt1c_57QTpP-UNUOwuy1XQ3ixPfgrmyq-J6zOICdJu0',
     'filename': 'WQ_BeachCleanups_5-16-2024_web.png',
     'size': 182441,
     'type': 'image/png',
     'thumbnails': {'small': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/Y3DWod2FnbExOs1d6sH3ZA/Mqet46yufnLz4R8fViSBTXyLaDVsswtN7HshwfMYMdzLvS9kvD2sGBszU4bZb4u-mjv7VSk6w-6xH1UDsaqlowdbWOx0_4zGr1ZruuXCSb46LCuZkR_oBJVrlOe-IuCu4YlQykZ--eayBi4MwYlACA/yIWgNBjIFooUHsw_8vFQopYbt2i0ARGtJHqN02IYZmg',
       'width': 56,
       'height': 36},
      'large': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/YPsaU2YF7PxCGYBijjENtA/7a2ikTHulUvwzh6Y5t4OZSMmj4ivUAhq46QDIY5RhRlarawsWYEB7DMWOvwkozDQ86F239sACA4tr8I7Muc0DCe-WKKGwDClU0fGUiWM-s9_i9XFCKu49QtKHY2nr8yTo7CcC9ocG9eKFQXqAP4lmA/UQHf0Lg_fWGyhV_7dovNcsGcf3M5L6C926Iy0L2FE4A',
       'width': 790,
       'height': 512},
      'full': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/2s4bSrd1A2AK1xVsBYTriQ/Coc2wHKxwVQu4eKIC4bR7aQXiG1MOF_618usjxB-QCwvNGWsoP9Ay1CmuNIuBeGeUryFYQj-ow624FtVhThRnRySrYJ_lYLgQlJQlnxBTXjqlbO0qsWryQFXzlQDFgq2MPt0RhwZTUTToL7eakvhaA/UzQDBlLSnrVz8e9qjfalC6OkMBdt_dcpi97J1VHhCgg',
       'width': 3000,
       'height': 1944}}}],
   'Trend_text': 'Improving',
   'Viz-2': [{'id': 'attvrSTJfoCTtW317',
     'width': 3750,
     'height': 2251,
     'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/yVUOF5VvJ6RHjwFQGMk1KA/Z-8IHiw1lPOThfxS43ah-R415AdtgcZtDHECv16EdodRz7diVOF_Cmf9WONYbzDT8KI9JhEpc23NeLaExGW3QTwcBf6eWMVUU-_muK5G4gOBvnURlf-OY7_Et_NnKHDfvTzBfb9Qa6outb5yxFCl_rM6OyXfG5hc_Ij25wtuqg4Vq8ZopRiDY9Luj3aEALXO/WVIchHN5lFFPP4AzpyBnOpNIFaynd8X12R6wHB3cjRI',
     'filename': 'WQ_BeachCleanups_09102024_web.png',
     'size': 116146,
     'type': 'image/png',
     'thumbnails': {'small': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/wv86m4_QAYFwS0s62MEjyA/1wFIZkTzmIJA_pHnlE_AuIQ-f7boKr0NIJFpoLCfn32Yu9r0eufdYHmUDT8W6hSkWrJZXZkhSzCDchkkFtKjbfFJJDrdxPMi6zP2e5wQKqxUBOUAjWHAKhVRjmbzFdrLS29kDlP-4ktpDTjOv5gy1Q/blxor3bXKaLib4N-r0D1TGze7Qy55xXWU3KvHbD3HVM',
       'width': 60,
       'height': 36},
      'large': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/7psiqs4w_A2vQ8ajqs87Xg/pV1-rolDSesaVz3OnptHFiitm3lL0nxxF_9JNI0Rw5gQc03fXEYn3YUu9-lIkV9pMFiGdrqNI1tp5hgjwrYz8X22d2URQSc_MQWc0XEViysTeyfbsWPNU7o4iW1FuI2ZbSBmicUr5L63HOrFlH6GcA/4AKSvVvqzYYxlOvmtJ9I9jFxyUvUhk5el_Q1BX1jV_s',
       'width': 853,
       'height': 512},
      'full': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/4OjJZ0j_veX1KqoeEIVjsg/e-Tno7agqGFg1gGDpOrc-C46jy3yZct7CgwSrioezo4UeqJh2C_w7IKtS2gsl_IfvDcMfr7_QnOaWgNbL9WMwZZMHCJ8kaqALtnvxuX-Z2Ogr1w7F1cU3TqGp2ijJkzZf1sEsXO0ssLucHkdeGEU3A/QmvNhE8qQiaqgTR7bMDHvygOReq4xOqhx_DFT1MTGXM',
       'width': 3000,
       'height': 1801}}}],
   'Callout_img': [{'id': 'attFcr6KCC061Tcod',
     'width': 3264,
     'height': 2448,
     'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/NgNF3VB41Xe0jaJaMNv_1w/fmkDOGUx2wgc4AbOJqPoyuKV9FJIFrpBbi1LxMiRSmytj3E0q--b-0zARCfNxcJlTuP_yibbMcQwiDnLRw6x_MYNLzbB9swrJm9uGWYh82MBh0XmQxBDlSh5sd6aABQ7Pz4-RgKQ5SFdDRcq_h3aJvbtR76StnCb29tnU47RWMI4NQYRFZLrfroOwH6wPWxJhbZZmAfgC0pj4C2Ic4GDiQ/Gun6ddTI7u9wbYs2EEpnhBsON3gZiysrugRj92lZySM',
     'filename': 'Floatables-Microplastics_Pollution_CreditKateBoicourt.JPG',
     'size': 4243667,
     'type': 'image/jpeg',
     'thumbnails': {'small': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/vNFc2mSA6gfzJrLseqn16Q/VLsTHXV118t5oRhDU5nHxbU4ku8JBvf4FBcdHV5yKrIsR65Yfj1C7aiNUyg1TzOy32yspIIygKWmvqZHN5vyAoB6iw2mFnlZccmknhaCu6SQba4lfgc2pbwRJOSI-4NUvMPyO1w-HAMjRmKaNaG8AA/pWvnJr3tpyPiMAkICV3wns7UI9Vdv2h5B2DYlaWcICQ',
       'width': 48,
       'height': 36},
      'large': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/g_4WzzrC5WZ1M5Zegmpplw/j_lwkT_lwaQ8sgF-Cl3uuaqUbPs5CMNrh0OXd0Q5FLOI4JhIeuyo9P9hvqiAArG1_sGBqu9z525LrJOE2T2sP4cjb_3R67-7bSOKZUDISPRU4VZWV92yFudSXex-KSvFqVpO2uBHWfW9r1Pq8Jlp4g/vA4BgDQunCAojEEmCTj1rhJuLsZVGfmbe2PICylhGsk',
       'width': 683,
       'height': 512},
      'full': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/0CGA79T4VXpS_ceYsRxyHA/8O9mU6u05KqNgNL8ff7DXGuONRj8A1gENM_54dLqrwHBeYMlEEz40wmfCIPdT1bLMtNfH0o2BQa4lTJk0n7Q9b8lOf7R6AAw68Z-B9lWIriCquxx7C560OJUa0O2epjvDFBnPvK1DKgkRWTN0SQynw/t_u2h0WwmLA7WuAI2ksM9L5mv6x_t35wBWUwxqbwK-g',
       'width': 3000,
       'height': 2250}}}],
   'Template': 'rows',
   'Link': 'debris',
   'Data Sources': 'Ocean Conservancy, NJDEP, Hudson Riverkeeper, USACE, PVSC, NYCDEP\n',
   'Topic': 'Water Quality',
   'bg-img': [{'id': 'attc9PxQBGvQeMgdu',
     'width': 3024,
     'height': 4032,
     'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/FqcqTc1wOq2USJrMxOPYEg/mAwqLWe2AGovPRrkKgDyjOY47lpYR4R8-qzjEzP9sSA4qUI20jfHrKXUdoDj3DX0h-qxGg5MSs2Li2RvNWPnQmk4sKLZJDBgXIKkF0hKHnE3ciFuHNaCFvigYgpKR2sX7W3DdngXWafbmqDJgzZtdMxtW5PqsPzYFORsSeosFaYGA9y-G64zOh_se_hEdwncU4zRu57Gq45p-7KmZSRF3A/6LgM_vhW7jTEe0QzN6yodKSFd9gxkkztqEdRW4DjeAQ',
     'filename': 'FloatableDebris_StoppingTrash-Hoboken_rpn.jpg',
     'size': 2785228,
     'type': 'image/jpeg',
     'thumbnails': {'small': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/u0jWoeghGT9fyyaujf7hIQ/rP2XKI2Ixfjzng2tFJGDiXWLdVzXNmXVxNBSUV-dVWRGXOoHGypliWcpQHdvnoAWX953Iak-mV8t6x2d2Hs5ZiyZyWyQu_C4x3o95I1u4WfHVdMrZfdRz4dLk7cqISKv4n5q9tKMpgOkajB8KvMOzQ/g60OQC51M8a3qZE4Hs0dmeLMw9R3AJ6-QquHro7n4Cw',
       'width': 27,
       'height': 36},
      'large': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/4uv1dWtvxqD5borYcJuEfw/X3HoDwjNEThOT-IyH-HRx0TEc3V3za_kbBgP-qZ0KIfMyP02HaWUQj1diGXc5RBet3F0s7nDTCqw8N9H-1oj1L0yv26YySSed6SRvSJO8i3GPMnjXOMaAIBcbEjqzAjdQ0AoI-TRr5W57y8Ua7uNtw/U9jnC9YMWueyiVvFe9x7VuV6A6rT3wwGYKPE0zzRnYM',
       'width': 512,
       'height': 683},
      'full': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/WNS-kT3ZJRaQn1vgTMUXxQ/wravsFYWRW26U2QaZhOCBIM6z1zblGEqfm-3K4E5Nixs729dR9BPWMgtKSDSqjrmeYYitp68FHirD5a7sC7PPcHN95ePEdoZXPUu2tRu4pQcYtZMi3W7RtlJU2CqHaDs1LlEIELUyvzXpzKOoEMZSQ/BjqtFlmB0CapC8Rf8JjnjkCBqX1SpP3O6u1eroPCfls',
       'width': 2250,
       'height': 3000}}}],
   'Photo Credits': 'Pedra Nobre, Boicourt\n',
   'Indicator': 'Floatable Debris',
   'Citations': '1. Colon, T. (2021). _Microplastics in the Big Apple: A look into plastic pollution of New York City Waters_ [Student Theses 2015-Present, Fordham University]. <https://research.library.fordham.edu/environ_2015/114>\n2. Polanco, H., Hayes, S., Roble, C., Krupitsky, M., & Branco, B. (2020). The presence and significance of microplastics in surface water in the Lower Hudson River Estuary 2016–2019: A research note. _Marine Pollution Bulletin_, _161_, 111702. <https://doi.org/10.1016/j.marpolbul.2020.111702>\n3. Miller, R. Z., Winslow, B., Kapp, K., Osborne, A., & Gwinnett, C. (2024). Microplastic and anthropogenic microfiber pollution in the surface waters of the East River and Long Island Sound, USA. _Regional Studies in Marine Science_, _70_, 103360. <https://doi.org/10.1016/j.rsma.2023.103360>\n4. Sipps, K., Arbuckle-Keil, G., Chant, R., Fahrenfeld, N., Garzio, L., Walsh, K., & Saba, G. (2022). Pervasive occurrence of microplastics in Hudson-Raritan estuary zooplankton. _Science of The Total Environment_, _817_, 152812. <https://doi.org/10.1016/j.scitotenv.2021.152812>\n5. Miller, R. Z., Watts, A. J. R., Winslow, B. O., Galloway, T. S., & Barrows, A. P. W. (2017). Mountains to the sea: River study of plastic and non-plastic microfiber pollution in the northeast USA. _Marine Pollution Bulletin_, _124_(1), Article 1. <https://doi.org/10.1016/j.marpolbul.2017.07.028>\n6. Galgani, F., Brien, A. S., Weis, J., Ioakeimidis, C., Schuyler, Q., Makarenko, I., Griffiths, H., Bondareff, J., Vethaak, D., Deidun, A., Sobral, P., Topouzelis, K., Vlahos, P., Lana, F., Hassellov, M., Gerigny, O., Arsonina, B., Ambulkar, A., Azzaro, M., & Bebianno, M. J. (2021). Are litter, plastic and microplastic quantities increasing in the ocean? _Microplastics and Nanoplastics_, _1_(1), Article 1. <https://doi.org/10.1186/s43591-020-00002-8>\n7. Ryan, M. G., Watkins, L., & Walter, M. T. (2019). Hudson River juvenile Blueback herring avoid ingesting microplastics. _Marine Pollution Bulletin_, _146_, 935–939. <https://doi.org/10.1016/j.marpolbul.2019.07.004>\n8. Boni, W., Arbuckle-Keil, G., & Fahrenfeld, N. L. (2022). Inter-storm variation in microplastic concentration and polymer type at stormwater outfalls and a bioretention basin. _Science of The Total Environment_, _809_, 151104. <https://doi.org/10.1016/j.scitotenv.2021.151104>\n',
   'Text-2': '### **Boom and Skim**\nThis improving trend on beaches is also matched by boom and skim collection in open water, which while maintaining a consistent effort, have shown a decrease in the amount of debris collected annually since 2001. The decrease in floatable debris is the result of coordinated efforts from both states to reduce floatable debris in the Estuary. In 1999, the New Jersey Department of Environmental Protection (NJDEP) required all combined sewer overflow (CSO) permit holders to implement floatable controls, which was completed in 2003. In 2015, New York City received its first Municipal Separate Storm Sewer System (MS4) Permit, required by the Clean Water Act to reduce pollution in stormwater runoff. This includes catch basins with hood screens on their stormwater inlets that keep floatable debris from entering the waterways.\xa0\xa0\n',
   'Background': 'Floatable debris, or garbage, in Estuary waters and shorelines affects the quality of waterfront parks and beaches, the costs of managing them, and the health of fish and wildlife. Larger debris can interfere with navigation and the growth of wetlands and other shoreline plants. Floating trash can enter the waterways by flowing out of sewer and stormwater drains, being dumped on shorelines, or being blown to the water by the wind. It is an easily visible indicator of water pollution. Shoreline cleanups have been an increasingly popular method of stewardship, bringing together community and business partners for an activity with tangible benefits. Many of the environmental groups that organize beach cleanups keep track of the amount of garbage they remove and some even inventory what kind of garbage they find.\n',
   'Text-1': '### **Beach Cleanups**\nThe amount of floatable debris collected from beach cleanups (by weight), standardized per mile of cleanup, has decreased since the early and mid-2000s, showing improvement in the amount of garbage pollution in the Estuary.\n'}},
 {'id': 'recZQEaJGpA2LjHbp',
  'createdTime': '2024-06-24T17:24:26.000Z',
  'fields': {'Trend': 'trend_up_green',
   'Viz-1': [{'id': 'attcQSqomlTfIA36D',
     'width': 3750,
     'height': 3372,
     'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/XvnkGn_U1sZL5ZnL8FWkxw/mFSkUa-fGZSv8efIjkJS-KdRruROy9yHgAadiwyyWUzQYx1x0Wxd00uIQNgEZgg1OuuyC7qeC_Gbm4lNpoCwh8XpN_eVDbe6PB5hMj-jTTHA4Kz-FMGdModlUwm4jI9KAqoIFTXRb_QKm1gEE4KMcZsmpbrJzl-Q8jGLe0PwSrs/Kp-QbA84qARG-i_CvtESQgz5HIU-3eHPRc2m-a9rom4',
     'filename': 'WQ_Nutrients_N_web.png',
     'size': 332496,
     'type': 'image/png',
     'thumbnails': {'small': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/36tG0OveLujJAK19dGxyqw/g0j4n8Qd3kQBk31B1K1MMuDWac9djl3K-Vk2UHd3fE3Oso5UU3HWanR3UvM8fMncBxs54iXKJ8c3RGdZeZOyJWmUt_Y_2CqVVDEM7tnfNF3KUWxk1MSXRMEa3aeNBqur0tFn69tJeen9KL6UjnX2XA/1ZgbcBT4mSdgJqWPBmMSitya1Y0RQ-X7eAzt7_20_VQ',
       'width': 40,
       'height': 36},
      'large': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/o_qufXk_CpROFd4zPvJvnw/YKa8yD6dN-t2Am3wcUHO54Z_c00rNEY0riAk7tde3cdylDJPaRVkJdxeBeyW2vSYQRMII3Fh_4_7FhsQLTLHK5spWWRAI7_gShvOFJNc7rxB2ElBD7KogS8sh_4G-o01ik4iVE500MwvOQj123kiKA/-ZIVp_F4MwlM_lgSieHNUFzp_IKZaCrHN-ba6UEOu4A',
       'width': 569,
       'height': 512},
      'full': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/4el-18sH_BSc8IpLsyvUog/6KySYxt4tEbMuD5poOw4MHEW-921GlDxe3ZVDQJHfEitEH8jhRDHU82_68U23bf-T2HK49E1Jh_TDe2nvpCDqP-pbmx-PWPMeQxrq0nyQQcJsaxjYGxSd48OkAXwkYP4fSxm5oEhuTCpU78e87GtVQ/wdz6F6Y8GVBGsqFPnTlpb_hlsHCFBA37a5HakSHif3Q',
       'width': 3000,
       'height': 2698}}}],
   'Trend_text': 'Improving',
   'Viz-2': [{'id': 'attqmI2QhDu13uRvk',
     'width': 3715,
     'height': 3029,
     'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/c3_nUioDg38DWYikdN9y0Q/W1hh7biCOLu5LvOrrPgbBR2q3jWKhIcO3RFxBAroO2Yjq28QKvBbOkvpWeh6CnRlwTCasuP6VAyAVw3tfHcA7NyAbV4n38yUlte8viAnBsjcMMtneSqlCEkRjLO5CcZ2G3NnAsS6lBDwN4F7bvok5tFBFtrHaLrkF5gA6WzWdjg/ZRuH5FBqerkSoq66ofcZxu5-HsVaVq6w0wA2V1KeCA0',
     'filename': 'WQ_Nutrients_P_web.png',
     'size': 260865,
     'type': 'image/png',
     'thumbnails': {'small': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/XlTekuJiZ4kIGXZcxYkLBg/wXWBwVYhRkw-tBjP41fuXZflvf0bL1wVVzPLKNstqSmFDSXOivBf2u8lmO9SjjfwFyHuNRgoaM_3Qwhl_I_c_fxFWgxqn4TtGaDdUIgBJQZequaAGX3AuHLKQT1Bqreb1KX4KLID8Gs7Up5PJZwe3A/dYOHA6Z8DjvkMWaU72I5RB1M6q0-SJxRW46LPW2DK6k',
       'width': 44,
       'height': 36},
      'large': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/bKdT8Mo1wB5N0YDH6QTN8w/nR2JPg0epw31SveG6g-9pczfHp6_ivr1ugQeUh0Q8ok22vEf2WBxeTtHe9GSPcZdEVl4APdWm0ocpxdXZ5S7v-JhTW6_4_KPxNIqE5k5NVpYHn_X_rTKTp9riMSY4dYbtPWJSMU8syribIQd1dIwig/SfE_wHGstkxbfe1BbEs2Fyr1mAGjqjkEzBSXD2Zs_nQ',
       'width': 628,
       'height': 512},
      'full': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/nWJeMKMPBWF0acx4LuZh0A/UKseS1a4RguRQtjnZxery-xHIA3XRbNcXM8KGH7SDLeY1znxcj0c_xkg5ScaSoOlqTgqntf2h3Ls2T8GQUR-mMLiU1I0dNFy1ciaQIfl777GtaE5eFStOlSYMiehrLobX5rghSGUZGgbm4ABJQ6otw/iSD61RPk8Qf7TAaux6pgZ5K70A8ixCyP0E62ekso8K8',
       'width': 3000,
       'height': 2446}}}],
   'Template': 'rows',
   'Viz-4': [{'id': 'attrDs1bHT05NHYsA',
     'width': 3750,
     'height': 3184,
     'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/nyl562y7PpgMoIXfVUXKew/eYRvCw_IQATrcQvUZP0tVgLW1u2lQ-pkD5ktsg64uXud8VROXk12H_n_jyEh-8DcnacaamAjoBmlkgGoQToYmVR7TtjClHbH2Nt8xCAg10ZjDTu8RT0d5bIw3k2h-mBD3nw--UgXJjEXqlgedWgC-lpIrONEV5wDxvIj2ejOpxc/dGl5Um2mGQ8AepNr5sfCv7Yyv5VwOUz1TW8bi2Q_mnE',
     'filename': 'WQ_Nutrients_DOC_web.png',
     'size': 357490,
     'type': 'image/png',
     'thumbnails': {'small': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/1E_dpx9lQeVnTOsADWshrQ/KWwyJhYCNipNJm6ZaioHfBRZqt-9KZoo1RRDI9rnjUBe8VoBBccmGBFCJ_vcsYzZEthtP3TFmV1CCgj6ZeAeqjFIyZ_AqNhHPI2E8_aik7PVDsc8zleRHG3Bq-HUkAYCofuNuS_wUm99Fs24y3IEaQ/eFcoK9u83PHPhzvQnRCUj6EG-9lKLBInOsqBvt2PIU8',
       'width': 42,
       'height': 36},
      'large': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/owoFM_bqzUsoobiW5v0pIA/dy8Wu2Xs53ah6btCLdaAk6ev8lbVr_4w6uKF3g2p6Ggzz8QjH_NNNVS5gwBjBRwWCZ941oKtgfOqO7traIxz8QmFuCyftx1EAVyrE3_vpIWnRlgZjCtAPz_tk_bBFSi4Aids3hN2nN5N5_5dbTpyKA/M8sL98tp0662nir_zHj1xRGB2sLsILEyYFFldSMDdKc',
       'width': 603,
       'height': 512},
      'full': {'url': 'https://v5.airtableusercontent.com/v3/u/37/37/1736812800000/8mPblZ_Syhon6-JqDCHp8g/Q_Kaoymc4c8ndYRI8SoWaruvptleb-mznW28x1nAyeIn2zcM9xY0RoBPLnUZ9PtxRUWckJSiHnO8F1oc9WTgeJpY8A-evzJQBoVJXJy_NMrZ74kpQM4VRy7jbYYzg79Hr1e2N8ToMJLYbcPFzNAx7w/6M3bCo6eDR0vKjeB9VieUfGqPEmM8zwf-gbdBK8IBss',
       'width': 3000,
       'height': 2547}}}],
   'Link': 'nutrients',
   'Data Sources': 'NYCDEP, NJHDG\n',
   'Topic': 'Water Quality',
   'Photo Credits': '\n',
   'Indicator': 'Nutrients',
   'Citations': '1. Phillips, P. J., & Hanchar, D. W. (1996). _Water-quality assessment of the Hudson River basin in New York and adjacent states: Analysis of available nutrient, pesticide volatile organic compound, and suspended-sediment data, 1970-90_. U.S. Geological Survey. <https://doi.org/10.3133/wri964065>\n2. Griffith, D. R., & Raymond, P. A. (2011). Multiple-source heterotrophy fueled by aged organic carbon in an urbanized estuary. _Marine Chemistry_, _124_(1), 14–22. <https://doi.org/10.1016/j.marchem.2010.11.003>\n3. NYSDEC. (2014). _Nonpoint Source Management Program_. Division of Water. <https://extapps.dec.ny.gov/docs/water_pdf/2014npsmgt.pdf>\n4. EcoCheck. (2013). _Sampling and data analysis protocols for Mid-Atlantic non-tidal stream indicators_. IAN Press.\n5. Coelho, J. P., Flindt, M. R., Jensen, H. S., Lillebø, A. I., & Pardal, M. A. (2004). Phosphorus speciation and availability in intertidal sediments of a temperate estuary: Relation to eutrophication and annual P-fluxes. _Estuarine, Coastal and Shelf Science_, _61_(4), 583–590. <https://doi.org/10.1016/j.ecss.2004.07.001>\n6. Meals, D. W., & Dressing, S. A. (2008). _Lag time in water quality response to land treatment_ (Developed for U.S. Environmental Protection Agency) [Tech Notes 4]. Tetra Tech, Inc. <https://www.epa.gov/polluted-runoff-nonpoint-source-pollution/nonpoint-source-monitoring-technical-notes>\n7. Tzortziou, M., Neale, P. J., Osburn, C. L., Megonigal, J. P., Maie, N., & Jaffé, R. (2008). Tidal marshes as a source of optically and chemically distinctive colored dissolved organic matter in the Chesapeake Bay. _Limnology and Oceanography_, _53_(1), 148–159. <https://doi.org/10.4319/lo.2008.53.1.0148>\n',

In [7]:
data = [i['fields'] for i in data]
df = pd.DataFrame(data)

df.head()

,Callout_text_1,Trend,Viz-1,Trend_text,Viz-2,Callout_img,Template,Link,Data Sources,Topic,...,Text-5,Viz-5,ia-chart,Findings_text,Callout_text_2,Viz-7,Text-8,Viz-6,Text-6,Text-7
0,### **Microplastics**\n\nWhile floatable debri...,trend_up_green,"[{'id': 'att9guhUfwBilljZB', 'width': 3750, 'h...",Improving,"[{'id': 'attvrSTJfoCTtW317', 'width': 3750, 'h...","[{'id': 'attFcr6KCC061Tcod', 'width': 3264, 'h...",rows,debris,"Ocean Conservancy, NJDEP, Hudson Riverkeeper, ...",Water Quality,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,trend_up_green,"[{'id': 'attcQSqomlTfIA36D', 'width': 3750, 'h...",Improving,"[{'id': 'attqmI2QhDu13uRvk', 'width': 3715, 'h...",NaN,rows,nutrients,"NYCDEP, NJHDG\n",Water Quality,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,trend_varied,"[{'id': 'att4MULblF9ZqgtxW', 'width': 2917, 'h...",No trend,"[{'id': 'attUR2dh8QAaE5D6b', 'width': 1050, 'h...",NaN,interactive chart,do,"NYCDEP, NJHDG, HRECOS\n",Water Quality,...,Another complicating factor in analyzing disso...,"[{'id': 'att0KYqxgmDuPoAME', 'width': 3672, 'h...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,### **Precipitation**\nClimate change does not...,trend_varied,"[{'id': 'attzwOxdYeNfYb22a', 'width': 3684, 'h...",No trend,"[{'id': 'attfZcr3BHKT3yhTF', 'width': 3727, 'h...","[{'id': 'attBdnPccBCv4lnwX', 'width': 3085, 'h...",rows,pathogens,"NYCDEP, NJHDG, Citizens Water Quality Testing ...",Water Quality,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,### **Salinity**\nSalinity is defined as the c...,trend_varied,"[{'id': 'attuZX8R1t9bnMav1', 'width': 1050, 'h...",No trend,NaN,NaN,rows,ph,HRECOS\n,Water Quality,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.columns

Index(['Callout_text_1', 'Trend', 'Viz-1', 'Trend_text', 'Viz-2',
       'Callout_img', 'Template', 'Link', 'Data Sources', 'Topic', 'bg-img',
       'Photo Credits', 'Indicator', 'Citations', 'Text-2', 'Background',
       'Text-1', 'Viz-4', 'Text-3', 'Text-4', 'Viz-3', 'Text-5', 'Viz-5',
       'ia-chart', 'Findings_text', 'Callout_text_2', 'Viz-7', 'Text-8',
       'Viz-6', 'Text-6', 'Text-7'],
      dtype='object')

In [26]:
vizCols = ['Topic','Indicator','Viz-1','Viz-2','Viz-3', 'Viz-4', 'Viz-5', 'Viz-6', 'Viz-7','bg-img', 'Callout_img' ]
df_img = df[vizCols]

df_img.head()

,Topic,Indicator,Viz-1,Viz-2,Viz-3,Viz-4,Viz-5,Viz-6,Viz-7,bg-img,Callout_img
0,Water Quality,Floatable Debris,"[{'id': 'att9guhUfwBilljZB', 'width': 3750, 'h...","[{'id': 'attvrSTJfoCTtW317', 'width': 3750, 'h...",NaN,NaN,NaN,NaN,NaN,"[{'id': 'attc9PxQBGvQeMgdu', 'width': 3024, 'h...","[{'id': 'attFcr6KCC061Tcod', 'width': 3264, 'h..."
1,Water Quality,Nutrients,"[{'id': 'attcQSqomlTfIA36D', 'width': 3750, 'h...","[{'id': 'attqmI2QhDu13uRvk', 'width': 3715, 'h...",NaN,"[{'id': 'attrDs1bHT05NHYsA', 'width': 3750, 'h...",NaN,NaN,NaN,NaN,NaN
2,Water Quality,Dissolved Oxygen,"[{'id': 'att4MULblF9ZqgtxW', 'width': 2917, 'h...","[{'id': 'attUR2dh8QAaE5D6b', 'width': 1050, 'h...","[{'id': 'att1Rk8F72jp9SaO0', 'width': 3564, 'h...","[{'id': 'attEICJB1dewCHcz7', 'width': 3494, 'h...","[{'id': 'att0KYqxgmDuPoAME', 'width': 3672, 'h...",NaN,NaN,"[{'id': 'attKMN4qQwu31P9Ec', 'width': 4000, 'h...",NaN
3,Water Quality,Pathogens,"[{'id': 'attzwOxdYeNfYb22a', 'width': 3684, 'h...","[{'id': 'attfZcr3BHKT3yhTF', 'width': 3727, 'h...","[{'id': 'att1vXUbMTS7n7Zvn', 'width': 3713, 'h...","[{'id': 'att4u5ZvAnHISnDST', 'width': 3000, 'h...",NaN,NaN,NaN,NaN,"[{'id': 'attBdnPccBCv4lnwX', 'width': 3085, 'h..."
4,Water Quality,pH,"[{'id': 'attuZX8R1t9bnMav1', 'width': 1050, 'h...",NaN,NaN,NaN,NaN,NaN,NaN,"[{'id': 'attVR3oRYAIj5ttix', 'width': 3024, 'h...",NaN

In [29]:
target_folder = r"C:\Users\cansu\Dropbox\HEP_2023\collected_graphics_01132025\All_images"
topics = df['Topic'].unique()

# create a folder for each topic
import os
for topic in topics:
    os.makedirs(os.path.join(target_folder, topic), exist_ok=True)

In [31]:
for i,r in df.iterrows():
    indicator = r['Indicator']
    topic = r['Topic']

    os.makedirs(os.path.join(target_folder, topic, indicator), exist_ok=True)

In [41]:
r

Topic                                              Water Quality
Viz-1          [{'id': 'attcQSqomlTfIA36D', 'width': 3750, 'h...
Viz-2          [{'id': 'attqmI2QhDu13uRvk', 'width': 3715, 'h...
Viz-3                                                        NaN
Viz-4          [{'id': 'attrDs1bHT05NHYsA', 'width': 3750, 'h...
Viz-5                                                        NaN
Viz-6                                                        NaN
Viz-7                                                        NaN
bg-img                                                       NaN
Callout_img                                                  NaN
Name: Nutrients, dtype: object

In [55]:
if len( r['Callout_img'] ) > 0:
    for callout_img in r['Callout_img']:
        callout_imgs.append(callout_img['url'])
else:
    callout_imgs = []

In [58]:
if isinstance(r['Callout_img'], list):
    # Handle the case where Callout_img is a list
    print("Callout_img is a list")
elif pd.isna(r['Callout_img']):
    # Handle the case where Callout_img is NaN
    print("Callout_img is NaN")
else:
    # Handle other cases if necessary
    print("Callout_img is neither a list nor NaN")

Callout_img is NaN

In [59]:
import time

for i,r in df_img.set_index('Indicator').iterrows():
    
    print( r['Topic'] , i)
    # Get the images, URL's
    if not pd.isna(r['bg-img']): bg_img = r['bg-img'][0]['url']
    
    callout_imgs = []
    if isinstance(r['Callout_img'], list):
        # Handle the case where Callout_img is a list
        for callout_img in r['Callout_img']:
            callout_imgs.append(callout_img['url'])
    elif pd.isna(r['Callout_img']):
        continue
    else:
        # Handle other cases if necessary
        continue

    charts = []
    for viz in ['Viz-1','Viz-2','Viz-3', 'Viz-4', 'Viz-5', 'Viz-6', 'Viz-7']:
        if not pd.isna(r[viz]):
            charts.append(r[viz][0]['url'])

    # Download
    # 1. save BG Image
    response = requests.get(bg_img)

    if response.status_code == 200:
        with open( os.path.join(target_folder, r['Topic'],i, f"{i}_bg_img.jpg"), "wb") as file:
            file.write(response.content)

    # 2. save Callout Images
    for idx, callout_img in enumerate(callout_imgs):
        response = requests.get(callout_img)

        if response.status_code == 200:
            with open( os.path.join(target_folder, r['Topic'],i, f"{i}_callout_img_{idx}.jpg"), "wb") as file:
                file.write(response.content)

    # 3. save Charts
    for idx, chart in enumerate(charts):
        response = requests.get(chart)

        if response.status_code == 200:
            with open( os.path.join(target_folder, r['Topic'],i, f"{i}_chart_{idx}.jpg"), "wb") as file:
                file.write(response.content)

    time.sleep( 2 )

Water Quality Floatable Debris
Water Quality Nutrients
Water Quality Dissolved Oxygen
Water Quality Pathogens
Water Quality pH
Water Quality Water Temperature
Water Quality Turbidity
Habitat Riparian Area Integrity
Habitat Tributary Habitat Connectivity
Habitat Horseshoe Crab Spawning
Habitat Area of Tidal Wetlands
Habitat Established Oyster Beds
Habitat Estuarine & Diadromous Fish Abundance
Habitat Percent & Distribution of Natural Shorelines
Habitat Stream Health Bioassessment
Habitat Submerged Aquatic Vegetation
Contaminants Cadmium
Contaminants PAHs
Contaminants PCBs
Community Engagement Coverage of Stewardship Organizations
Community Engagement Participation in Community Science
Community Engagement Participation in Stewardship Events
Public Access Direct Public Access Points
Public Access On-Water Programs
Public Access Publicly Accessible Waterfront in Overburdened Communities
Public Access Shoreline Access Over Time
Public Access Open Water Swimming Events

In [47]:

if (len(r['Callout_img']) > 0) and (not pd.isna(r['Callout_img'])):
    print( 'momo' )

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()